### PR TITLE
Fix data sources with output-typed inputs

### LINKED ISSUE #67: `Output<T>` should not be passed as argument to datasource
`tf2pulumi` will currently generate code like this:

```ts
import * as pulumi from "@pulumi/pulumi";
import * as gcp from "@pulumi/gcp";

const myaccount = new gcp.serviceAccount.Account("myaccount", {
    accountId: "dev-foo-account",
});
const mykeyKey = new gcp.serviceAccount.Key("mykey", {
    serviceAccountId: myaccount.name,
});
const mykeyAccountKey = pulumi.output(gcp.serviceAccount.getAccountKey({
    name: mykeyKey.name,
    publicKeyType: "TYPE_X509_PEM_FILE",
}));
```

This is an error due to `mykeyKey.name` being an `Output<string>` which is not allowed as an input to a datasource projection like `getAccountKey`.

### PR DESCRIPTION
**Pull request by pgavlin**
Data sources with output-typed inputs need to be generated as a call to
`apply` that contains a call to the data source itself with the resolved
outputs. These changes implement this in a moderately subtle fashion:
instead of generating the data source ad-hoc, it is turned into an
intrinsic that is then handed over to the apply rewriter. If the apply
rewriter does not transform the intrinsic, the call to the data source
is wrapped in a call to `pulumi.output` in order to keep the generated
code in normal form.

Fixes #67.

### CODE REVIEW

File: gen/nodejs/hil.go [hunk 1]
```diff
@@ -212,6 +212,15 @@ func (g *generator) genCall(w io.Writer, n *il.BoundCall) {
 		g.genf(w, "new pulumi.asset.FileAsset(%v)", n.Args[0])
 	case "__coerce":
 		g.genCoercion(w, n.Args[0], n.Type())
+	case "__dataSource":
+		g.gen(w, n.Args[0].(*il.BoundLiteral).Value, "(")
+		for i, v := range n.Args[1:] {
```
Comment (pgavlin) [inline gen/nodejs/hil.go]: Note that this could just assert that there is only one argument past the name of the function call and generate it directly.

File: gen/nodejs/generator.go [hunk 2]
```diff
@@ -649,9 +652,30 @@ func (g *generator) generateResource(r *il.ResourceNode) error {
 
 	name := g.nodeName(r)
 	qualifiedMemberName := fmt.Sprintf("%s%s.%s", provider, module, memberName)
+
+	// Because data sources are treated as normal function calls, we treat them a little bit differently by first
+	// rewriting them into calls to the `__dataSource` intrinsic.
+	properties := il.BoundNode(r.Properties)
+	if r.Config.Mode != config.ManagedResourceMode {
+		properties = &il.BoundCall{
+			HILNode:  &ast.Call{Func: "__dataSource"},
```
Comment (swgillespie) [inline gen/nodejs/generator.go]: It would be useful to document the contract that these intrinsics have somewhere. For `__dataSource` it seems to be that argument 0 must be a literal String and argument 1 must be a map of outputs?

File: gen/nodejs/generator.go [hunk 3]
```diff
@@ -667,15 +691,23 @@ func (g *generator) generateResource(r *il.ResourceNode) error {
 			g.printf("%sconst %s = new %s(%s, %s%s);", g.indent, name, qualifiedMemberName, resName, inputs, explicitDeps)
 		} else {
 			// TODO: explicit dependencies
-			g.printf("%sconst %s = pulumi.output(%s(%s));", g.indent, name, qualifiedMemberName, inputs)
+
+			// If the input properties did not contain any outputs, then we need to wrap the result in a call to pulumi.output.
+			// Otherwise, we are okay as-is.
+			fmtstr := "%sconst %s = pulumi.output(%s);"
+			if transformed {
+				fmtstr = "%sconst %s = %s;"
```
Comment (swgillespie) [inline gen/nodejs/generator.go]: To check my understanding: We do not need to wrap the input bag in `pulumi.output` here because the apply rewriter has already transformed the input bag into an `apply` that massages the outputs from the other resource into the format expected by the data source?

File: gen/nodejs/generator.go [hunk 4]
```diff
@@ -693,7 +725,15 @@ func (g *generator) generateResource(r *il.ResourceNode) error {
 					inputs, explicitDeps)
 			} else {
 				// TODO: explicit dependencies
-				g.printf("%s%s.push(pulumi.output(%s(%s)));\n", g.indent, name, qualifiedMemberName, inputs)
+
+				// If the input properties did not contain any outputs, then we need to wrap the result in a call to pulumi.output.
+				// Otherwise, we are okay as-is.
+				fmtstr := "%s%s.push(pulumi.output(%s));\n"
+				if transformed {
+					fmtstr = "%s%s.push(%s);\n"
```
Comment (swgillespie) [inline gen/nodejs/generator.go]: It took me a few minutes to wrap my head around what `count` on a data source even means, but I can imagine it being marginally useful with `${count.index}`...

File: gen/nodejs/generator.go (hunk 2 above)
Comment (pgavlin) [reply gen/nodejs/generator.go]: It would be, yes. I plan on adding a library of helpers for constructing these calls.

Comment (pgavlin) [reply gen/nodejs/generator.go]: (and yes, that's the contract)

File: gen/nodejs/generator.go (hunk 3 above)
Comment (pgavlin) [reply gen/nodejs/generator.go]: Correct.

File: gen/nodejs/generator.go (hunk 4 above)
Comment (pgavlin) [reply gen/nodejs/generator.go]: It's useful when you want to fetch some property for a set of resources. Say for example you have a list of subnets and want to fetch the VPC IDs for each--then you would use a counted data source.
