### PR TITLE
Fix identifier generation

### LINKED ISSUE #28: Keys with hyphens and slashes not converted properly
A Terraform configuration that has resources with object keys with hyphens and slashes are not converted properly and result in invalid code. Some keys end up quoted and some do not. The behavior seems to differ for supported and unsupported plugins (via the `--allow-missing-plugins` flag).

Using `tf2pulumi` built from https://github.com/pulumi/tf2pulumi/commit/6703b77a35d543f67c24e8bb6585de4e35d6e56a.

Original code:
```hcl
resource "aws_instance" "web" {
  ami           = "ami-abc123"
  instance_type = "t2.micro"

  tags = {
    "regulartag"                = "v1"
    "tag-with-hyphens"          = "v1"
    "tag/with/path"             = "v1"
    "tag/with/path-and-hyphens" = "v1"
  }
}

resource "consul_key_prefix" "json" {
  datacenter  = "west"
  path_prefix = "path1/"

  subkeys = {
    "regulartag"                = "v1"
    "tag-with-hyphens"          = "v1"
    "tag/with/path"             = "v1"
    "tag/with/path-and-hyphens" = "v1"
  }
}
``` 

Converted code:
```typescript
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";
import * as consul from "@pulumi/consul";

const aws_instance_web = new aws.ec2.Instance("web", {
    ami: "ami-abc123",
    instanceType: "t2.micro",
    tags: {
        regulartag: "v1",
        tag-with-hyphens: "v1",
        tag/with/path: "v1",
        tag/with/path-and-hyphens: "v1",
    },
});
const consul_key_prefix_json = new consul.KeyPrefix("json", {
    datacenter: "west",
    pathPrefix: "path1/",
    subkeys: [{
        regulartag: "v1",
        "tag-with-hyphens": "v1",
        tag/with/path: "v1",
        "tag/with/path-and-hyphens": "v1",
    }],
});
```

### PR DESCRIPTION
**Pull request by pgavlin**
The first cut of the code responsible for turning arbitrary TF names
into valid JavaScript identifiers was woefully incomplete. These changes
reimplement that code to confrom with the ECMA-262 spec.

Fixes #28.

### CODE REVIEW

**Comment by pgavlin** [comment]
With these changes, the config from issue #28 correctly converts to

```
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";
import * as consul from "@pulumi/consul";

const aws_instance_web = new aws.ec2.Instance("web", {
    ami: "ami-abc123",
    instanceType: "t2.micro",
    tags: {
        regulartag: "v1",
        "tag-with-hyphens": "v1",
        "tag/with/path": "v1",
        "tag/with/path-and-hyphens": "v1",
    },
});
const consul_key_prefix_json = new consul.KeyPrefix("json", {
    datacenter: "west",
    pathPrefix: "path1/",
    subkeys: [{
        regulartag: "v1",
        "tag-with-hyphens": "v1",
        "tag/with/path": "v1",
        "tag/with/path-and-hyphens": "v1",
    }],
});
```

**Comment by pgavlin** [comment]
pulumi-aws also has a few examples that end up corrected:
```diff
diff --git a/sdk/nodejs/apigateway/integration.ts b/sdk/nodejs/apigateway/integration.ts
index 52759ad..71d498c 100644
--- a/sdk/nodejs/apigateway/integration.ts
+++ b/sdk/nodejs/apigateway/integration.ts
@@ -35,10 +35,10 @@ import {RestApi} from "./restApi";
  *     cacheNamespace: "foobar",
  *     httpMethod: aws_api_gateway_method_MyDemoMethod.httpMethod,
  *     requestParameters: {
- *         integration.request.header.X-Authorization: "'static'",
+ *         "integration.request.header.X-Authorization": "'static'",
  *     },
  *     requestTemplates: {
- *         application/xml: "{\n   \"body\" : $input.json('$')\n}\n",
+ *         "application/xml": "{\n   \"body\" : $input.json('$')\n}\n",
  *     },
  *     resourceId: aws_api_gateway_resource_MyDemoResource.id,
  *     restApi: aws_api_gateway_rest_api_MyDemoAPI.id,
```

File: gen/nodejs/generator.go [hunk 1]
```diff
@@ -59,18 +60,56 @@ type generator struct {
...
+// isLegalIdentifierPart returns true if it is legal for c to be part of a JavaScript identifier (besides the first
+// character) as per ECMA-262.
+func isLegalIdentifierPart(c rune) bool {
+	return isLegalIdentifierStart(c) || unicode.In(c, unicode.Mn, unicode.Mc, unicode.Nd, unicode.Pc)
+}
+
+// isLegalIdentifier returns true if s is a legal JavaScript identifier as per ECMA-262.
+func isLegalIdentifier(s string) bool {
+	reader := strings.NewReader(s)
+	c, _, _ := reader.ReadRune()
```
Comment (swgillespie) [inline gen/nodejs/generator.go]: Is it the case today that you can write a well-formed HCL program that has identifiers whose names are invalid Unicode code points? Based on my basic understanding of this repo it does seem like we'll occasionally promote things that are string literals (map keys)to bare identifiers, so I suppose my real question is: does HCL allow invalid Unicode in its strings?

File: gen/nodejs/generator.go [hunk 2]
```diff
@@ -59,18 +60,56 @@ type generator struct {
...
+
+// cleanName replaces characters that are not allowed in JavaScript identifiers with underscores. No attempt is made to
 // ensure that the result is unique.
 func cleanName(name string) string {
-	if !strings.ContainsAny(name, " -.") {
-		return name
+	reader, writer := strings.NewReader(name), strings.Builder{}
+
+	// consume the leading character
+	c, _, err := reader.ReadRune()
```
Comment (swgillespie) [inline gen/nodejs/generator.go]: Is it possible to use the standard go `for _, c := range name` here? Go doesn't guarantee that the slice of bytes contained in a string is valid UTF-8 or makes sense when understood as Unicode, but does HCL?

Comment (pgavlin) [reply gen/nodejs/generator.go]: Ranging over a string as you suggest will range over its bytes, not its code points. We explicitly want to range over code points, as that is how ECMA describes the lexical grammar for identifiers. However, we _can_ change this to be `for _, c := range []rune(name)`.

Comment (pgavlin) [reply gen/nodejs/generator.go]: Disregard my earlier comment: this changed at some point pre-1.0 :)
